apiVersion: v2
name: vault-autounseal-operator
description: A Kubernetes operator for automatically unsealing HashiCorp Vault instances
type: application
version: 1.0.1
appVersion: "1.0.1"
keywords:
  - vault
  - hashicorp
  - operator
  - unsealing
  - kubernetes
home: https://github.com/panteparak/vault-autounseal-operator
sources:
  - https://github.com/panteparak/vault-autounseal-operator
maintainers:
  - name: Pan Teparak
    email: panteparak@gmail.com
