version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "panteparak"
    assignees:
      - "panteparak"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "panteparak"
    assignees:
      - "panteparak"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "ci"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "panteparak"
    assignees:
      - "panteparak"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"
