run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - errcheck
    - gosimple
    - staticcheck

linters-settings:
  govet:
    disable:
      - fieldalignment

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
