version: '3.8'

services:
  vault-dev:
    image: hashicorp/vault:1.20.0
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-dev", "-dev-root-token-id=root-token"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - vault-network

  vault-sealed:
    image: hashicorp/vault:1.20.0
    container_name: vault-sealed
    ports:
      - "8201:8200"
    volumes:
      - vault-data:/vault/data
      - ./test/vault-config:/vault/config
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]
    depends_on:
      - vault-storage
    healthcheck:
      test: ["CMD-SHELL", "vault status || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - vault-network

  vault-storage:
    image: consul:1.16.0
    container_name: vault-storage
    ports:
      - "8500:8500"
    command: ["consul", "agent", "-dev", "-client=0.0.0.0", "-ui"]
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - vault-network

  vault-integration-tests:
    build:
      context: .
      dockerfile: test/Dockerfile.integration
    container_name: integration-tests
    depends_on:
      vault-dev:
        condition: service_healthy
      vault-sealed:
        condition: service_healthy
      vault-storage:
        condition: service_healthy
    environment:
      VAULT_DEV_URL: http://vault-dev:8200
      VAULT_SEALED_URL: http://vault-sealed:8200
      VAULT_TOKEN: root-token
      GO_ENV: test
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    networks:
      - vault-network

volumes:
  vault-data:

networks:
  vault-network:
    driver: bridge
