version: '3.8'

# Scenario 1: Development Vault (unsealed, with root token)
services:
  vault-dev:
    image: hashicorp/vault:1.20.0
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-dev", "-dev-root-token-id=root-token"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
