apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-autounseal-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-autounseal-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "vault-autounseal-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-autounseal-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-autounseal-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: webhook
    port: 9443
    targetPort: 9443
    protocol: TCP
  selector:
    {{- include "vault-autounseal-operator.selectorLabels" . | nindent 4 }}
