apiVersion: vault.io/v1
kind: VaultUnsealConfig
metadata:
  name: vault-with-secret-ref
  namespace: vault
spec:
  url: "https://vault.example.com:8200"
  unsealKeys:
    secretRef:
      name: vault-unseal-keys
      namespace: vault
      key: keys
  namespace: vault
  podSelector:
    matchLabels:
      app: vault
      component: server
  threshold: 3
  haEnabled: true
  tlsSkipVerify: false
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
data:
  keys: WyJkR1Z6ZEMxMWJuTmxZV3d0YTJWNU9URT0iLCJaR1I2ZEMxMWJuTmxZV3d0YTJWNU9UST0iLCJaR1I2ZEMxMWJuTmxZV3d0YTJWNU9UTT0iXQ==  # base64 encoded JSON array of keys